/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Time = IDL.Int;
export const Article = IDL.Record({
  'categories' : IDL.Vec(IDL.Text),
  'title' : IDL.Text,
  'likeCount' : IDL.Nat,
  'content' : IDL.Text,
  'createdAt' : Time,
  'author' : IDL.Principal,
  'updatedAt' : Time,
  'pinned' : IDL.Bool,
  'hideReason' : IDL.Text,
  'visible' : IDL.Bool,
  'pinOrder' : IDL.Nat,
});
export const Comment = IDL.Record({
  'content' : IDL.Text,
  'commentId' : IDL.Nat,
  'createdAt' : Time,
  'author' : IDL.Principal,
  'articleId' : IDL.Nat,
});
export const UserProfile = IDL.Record({
  'name' : IDL.Text,
  'email' : IDL.Opt(IDL.Text),
});
export const _ImmutableObjectStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _ImmutableObjectStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _ImmutableObjectStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const Error = IDL.Variant({
  'FrontendOriginsNotConfigured' : IDL.Null,
  'MixedSsoSources' : IDL.Record({
    'otherKeys' : IDL.Vec(IDL.Text),
    'ssoKeys' : IDL.Vec(IDL.Text),
  }),
  'Stale' : IDL.Record({ 'ageNs' : IDL.Nat }),
  'MalformedCandid' : IDL.Null,
  'AmbiguousAttribute' : IDL.Record({
    'field' : IDL.Text,
    'sources' : IDL.Vec(IDL.Text),
  }),
  'NoAttributes' : IDL.Null,
  'UnknownNonce' : IDL.Null,
  'UntrustedSsoSource' : IDL.Record({ 'domain' : IDL.Text }),
  'MissingField' : IDL.Text,
  'FrontendOriginMismatch' : IDL.Record({
    'got' : IDL.Text,
    'expected' : IDL.Vec(IDL.Text),
  }),
});
export const Result = IDL.Variant({ 'ok' : IDL.Null, 'err' : Error });
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const FileReference = IDL.Record({
  'hash' : IDL.Text,
  'path' : IDL.Text,
});
export const ApprovalStatus = IDL.Variant({
  'pending' : IDL.Null,
  'approved' : IDL.Null,
  'rejected' : IDL.Null,
});
export const UserApprovalInfo = IDL.Record({
  'status' : ApprovalStatus,
  'principal' : IDL.Principal,
});

export const idlService = IDL.Service({
  '__accessControlState' : IDL.Func([], [IDL.Reserved], ['query']),
  '__approvalState' : IDL.Func([], [IDL.Reserved], ['query']),
  '__articleLikes' : IDL.Func([], [IDL.Reserved], ['query']),
  '__articles' : IDL.Func(
      [IDL.Opt(IDL.Nat), IDL.Opt(IDL.Nat)],
      [IDL.Vec(IDL.Tuple(IDL.Nat, Article))],
      ['query'],
    ),
  '__comments' : IDL.Func(
      [IDL.Opt(IDL.Nat), IDL.Opt(IDL.Nat)],
      [IDL.Vec(IDL.Tuple(IDL.Nat, Comment))],
      ['query'],
    ),
  '__ledgerState' : IDL.Func([], [IDL.Reserved], ['query']),
  '__nextArticleId' : IDL.Func([], [IDL.Nat], ['query']),
  '__nextCommentId' : IDL.Func([], [IDL.Nat], ['query']),
  '__nextPinOrder' : IDL.Func([], [IDL.Nat], ['query']),
  '__registry' : IDL.Func([], [IDL.Reserved], ['query']),
  '__userProfiles' : IDL.Func(
      [IDL.Opt(IDL.Principal), IDL.Opt(IDL.Nat)],
      [IDL.Vec(IDL.Tuple(IDL.Principal, UserProfile))],
      ['query'],
    ),
  '_immutableObjectStorageBlobsAreLive' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [IDL.Vec(IDL.Bool)],
      ['query'],
    ),
  '_immutableObjectStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_immutableObjectStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_immutableObjectStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_ImmutableObjectStorageCreateCertificateResult],
      [],
    ),
  '_immutableObjectStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_ImmutableObjectStorageRefillInformation)],
      [_ImmutableObjectStorageRefillResult],
      [],
    ),
  '_immutableObjectStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initialize_access_control' : IDL.Func([], [], []),
  '_internet_identity_sign_in_finish' : IDL.Func([], [Result], []),
  '_internet_identity_sign_in_start' : IDL.Func([], [IDL.Vec(IDL.Nat8)], []),
  'addComment' : IDL.Func([IDL.Nat, IDL.Text], [IDL.Nat], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createArticle' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Vec(IDL.Text)],
      [IDL.Nat],
      [],
    ),
  'deleteArticle' : IDL.Func([IDL.Nat], [], []),
  'deleteComment' : IDL.Func([IDL.Nat], [], []),
  'dropFileReference' : IDL.Func([IDL.Text], [], []),
  'getAllArticles' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(IDL.Nat, Article))],
      ['query'],
    ),
  'getArticle' : IDL.Func([IDL.Nat], [IDL.Opt(Article)], ['query']),
  'getArticleLikeCount' : IDL.Func([IDL.Nat], [IDL.Nat], ['query']),
  'getArticlesByAuthor' : IDL.Func(
      [IDL.Principal],
      [IDL.Vec(IDL.Tuple(IDL.Nat, Article))],
      ['query'],
    ),
  'getArticlesByCategory' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(IDL.Tuple(IDL.Nat, Article))],
      ['query'],
    ),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getCommentsForArticle' : IDL.Func([IDL.Nat], [IDL.Vec(Comment)], ['query']),
  'getFileReference' : IDL.Func(
      [IDL.Text],
      [IDL.Opt(FileReference)],
      ['query'],
    ),
  'getTokenBalance' : IDL.Func([], [IDL.Nat], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'hasLikedArticle' : IDL.Func([IDL.Nat], [IDL.Bool], ['query']),
  'initializeAccessControl' : IDL.Func([], [], []),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'isCallerApproved' : IDL.Func([], [IDL.Bool], ['query']),
  'likeArticle' : IDL.Func([IDL.Nat], [], []),
  'listApprovals' : IDL.Func([], [IDL.Vec(UserApprovalInfo)], ['query']),
  'listFileReferences' : IDL.Func([], [IDL.Vec(FileReference)], ['query']),
  'registerFileReference' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'requestApproval' : IDL.Func([], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'setApproval' : IDL.Func([IDL.Principal, ApprovalStatus], [], []),
  'setArticlePinned' : IDL.Func([IDL.Nat, IDL.Bool], [], []),
  'setArticleVisible' : IDL.Func([IDL.Nat, IDL.Bool, IDL.Text], [], []),
  'transferTokens' : IDL.Func([IDL.Principal, IDL.Nat], [], []),
  'unlikeArticle' : IDL.Func([IDL.Nat], [], []),
  'updateArticle' : IDL.Func(
      [IDL.Nat, IDL.Text, IDL.Text, IDL.Vec(IDL.Text)],
      [],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Time = IDL.Int;
  const Article = IDL.Record({
    'categories' : IDL.Vec(IDL.Text),
    'title' : IDL.Text,
    'likeCount' : IDL.Nat,
    'content' : IDL.Text,
    'createdAt' : Time,
    'author' : IDL.Principal,
    'updatedAt' : Time,
    'pinned' : IDL.Bool,
    'hideReason' : IDL.Text,
    'visible' : IDL.Bool,
    'pinOrder' : IDL.Nat,
  });
  const Comment = IDL.Record({
    'content' : IDL.Text,
    'commentId' : IDL.Nat,
    'createdAt' : Time,
    'author' : IDL.Principal,
    'articleId' : IDL.Nat,
  });
  const UserProfile = IDL.Record({
    'name' : IDL.Text,
    'email' : IDL.Opt(IDL.Text),
  });
  const _ImmutableObjectStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _ImmutableObjectStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _ImmutableObjectStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const Error = IDL.Variant({
    'FrontendOriginsNotConfigured' : IDL.Null,
    'MixedSsoSources' : IDL.Record({
      'otherKeys' : IDL.Vec(IDL.Text),
      'ssoKeys' : IDL.Vec(IDL.Text),
    }),
    'Stale' : IDL.Record({ 'ageNs' : IDL.Nat }),
    'MalformedCandid' : IDL.Null,
    'AmbiguousAttribute' : IDL.Record({
      'field' : IDL.Text,
      'sources' : IDL.Vec(IDL.Text),
    }),
    'NoAttributes' : IDL.Null,
    'UnknownNonce' : IDL.Null,
    'UntrustedSsoSource' : IDL.Record({ 'domain' : IDL.Text }),
    'MissingField' : IDL.Text,
    'FrontendOriginMismatch' : IDL.Record({
      'got' : IDL.Text,
      'expected' : IDL.Vec(IDL.Text),
    }),
  });
  const Result = IDL.Variant({ 'ok' : IDL.Null, 'err' : Error });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const FileReference = IDL.Record({ 'hash' : IDL.Text, 'path' : IDL.Text });
  const ApprovalStatus = IDL.Variant({
    'pending' : IDL.Null,
    'approved' : IDL.Null,
    'rejected' : IDL.Null,
  });
  const UserApprovalInfo = IDL.Record({
    'status' : ApprovalStatus,
    'principal' : IDL.Principal,
  });
  
  return IDL.Service({
    '__accessControlState' : IDL.Func([], [IDL.Reserved], ['query']),
    '__approvalState' : IDL.Func([], [IDL.Reserved], ['query']),
    '__articleLikes' : IDL.Func([], [IDL.Reserved], ['query']),
    '__articles' : IDL.Func(
        [IDL.Opt(IDL.Nat), IDL.Opt(IDL.Nat)],
        [IDL.Vec(IDL.Tuple(IDL.Nat, Article))],
        ['query'],
      ),
    '__comments' : IDL.Func(
        [IDL.Opt(IDL.Nat), IDL.Opt(IDL.Nat)],
        [IDL.Vec(IDL.Tuple(IDL.Nat, Comment))],
        ['query'],
      ),
    '__ledgerState' : IDL.Func([], [IDL.Reserved], ['query']),
    '__nextArticleId' : IDL.Func([], [IDL.Nat], ['query']),
    '__nextCommentId' : IDL.Func([], [IDL.Nat], ['query']),
    '__nextPinOrder' : IDL.Func([], [IDL.Nat], ['query']),
    '__registry' : IDL.Func([], [IDL.Reserved], ['query']),
    '__userProfiles' : IDL.Func(
        [IDL.Opt(IDL.Principal), IDL.Opt(IDL.Nat)],
        [IDL.Vec(IDL.Tuple(IDL.Principal, UserProfile))],
        ['query'],
      ),
    '_immutableObjectStorageBlobsAreLive' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [IDL.Vec(IDL.Bool)],
        ['query'],
      ),
    '_immutableObjectStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_immutableObjectStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_immutableObjectStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_ImmutableObjectStorageCreateCertificateResult],
        [],
      ),
    '_immutableObjectStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_ImmutableObjectStorageRefillInformation)],
        [_ImmutableObjectStorageRefillResult],
        [],
      ),
    '_immutableObjectStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initialize_access_control' : IDL.Func([], [], []),
    '_internet_identity_sign_in_finish' : IDL.Func([], [Result], []),
    '_internet_identity_sign_in_start' : IDL.Func([], [IDL.Vec(IDL.Nat8)], []),
    'addComment' : IDL.Func([IDL.Nat, IDL.Text], [IDL.Nat], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createArticle' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Vec(IDL.Text)],
        [IDL.Nat],
        [],
      ),
    'deleteArticle' : IDL.Func([IDL.Nat], [], []),
    'deleteComment' : IDL.Func([IDL.Nat], [], []),
    'dropFileReference' : IDL.Func([IDL.Text], [], []),
    'getAllArticles' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(IDL.Nat, Article))],
        ['query'],
      ),
    'getArticle' : IDL.Func([IDL.Nat], [IDL.Opt(Article)], ['query']),
    'getArticleLikeCount' : IDL.Func([IDL.Nat], [IDL.Nat], ['query']),
    'getArticlesByAuthor' : IDL.Func(
        [IDL.Principal],
        [IDL.Vec(IDL.Tuple(IDL.Nat, Article))],
        ['query'],
      ),
    'getArticlesByCategory' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(IDL.Tuple(IDL.Nat, Article))],
        ['query'],
      ),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getCommentsForArticle' : IDL.Func(
        [IDL.Nat],
        [IDL.Vec(Comment)],
        ['query'],
      ),
    'getFileReference' : IDL.Func(
        [IDL.Text],
        [IDL.Opt(FileReference)],
        ['query'],
      ),
    'getTokenBalance' : IDL.Func([], [IDL.Nat], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'hasLikedArticle' : IDL.Func([IDL.Nat], [IDL.Bool], ['query']),
    'initializeAccessControl' : IDL.Func([], [], []),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'isCallerApproved' : IDL.Func([], [IDL.Bool], ['query']),
    'likeArticle' : IDL.Func([IDL.Nat], [], []),
    'listApprovals' : IDL.Func([], [IDL.Vec(UserApprovalInfo)], ['query']),
    'listFileReferences' : IDL.Func([], [IDL.Vec(FileReference)], ['query']),
    'registerFileReference' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'requestApproval' : IDL.Func([], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'setApproval' : IDL.Func([IDL.Principal, ApprovalStatus], [], []),
    'setArticlePinned' : IDL.Func([IDL.Nat, IDL.Bool], [], []),
    'setArticleVisible' : IDL.Func([IDL.Nat, IDL.Bool, IDL.Text], [], []),
    'transferTokens' : IDL.Func([IDL.Principal, IDL.Nat], [], []),
    'unlikeArticle' : IDL.Func([IDL.Nat], [], []),
    'updateArticle' : IDL.Func(
        [IDL.Nat, IDL.Text, IDL.Text, IDL.Vec(IDL.Text)],
        [],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };