/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type ApprovalStatus = { 'pending' : null } |
  { 'approved' : null } |
  { 'rejected' : null };
export interface Article {
  'categories' : Array<string>,
  'title' : string,
  'likeCount' : bigint,
  'content' : string,
  'createdAt' : Time,
  'author' : Principal,
  'updatedAt' : Time,
  'pinned' : boolean,
  'hideReason' : string,
  'visible' : boolean,
  'pinOrder' : bigint,
}
export interface Comment {
  'content' : string,
  'commentId' : bigint,
  'createdAt' : Time,
  'author' : Principal,
  'articleId' : bigint,
}
export type Error = { 'FrontendOriginsNotConfigured' : null } |
  {
    'MixedSsoSources' : {
      'otherKeys' : Array<string>,
      'ssoKeys' : Array<string>,
    }
  } |
  { 'Stale' : { 'ageNs' : bigint } } |
  { 'MalformedCandid' : null } |
  { 'AmbiguousAttribute' : { 'field' : string, 'sources' : Array<string> } } |
  { 'NoAttributes' : null } |
  { 'UnknownNonce' : null } |
  { 'UntrustedSsoSource' : { 'domain' : string } } |
  { 'MissingField' : string } |
  { 'FrontendOriginMismatch' : { 'got' : string, 'expected' : Array<string> } };
export interface FileReference { 'hash' : string, 'path' : string }
export type Result = { 'ok' : null } |
  { 'err' : Error };
export type Time = bigint;
export interface UserApprovalInfo {
  'status' : ApprovalStatus,
  'principal' : Principal,
}
export interface UserProfile { 'name' : string, 'email' : [] | [string] }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _ImmutableObjectStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _ImmutableObjectStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _ImmutableObjectStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '__accessControlState' : ActorMethod<[], any>,
  '__approvalState' : ActorMethod<[], any>,
  '__articleLikes' : ActorMethod<[], any>,
  '__articles' : ActorMethod<
    [[] | [bigint], [] | [bigint]],
    Array<[bigint, Article]>
  >,
  '__comments' : ActorMethod<
    [[] | [bigint], [] | [bigint]],
    Array<[bigint, Comment]>
  >,
  '__ledgerState' : ActorMethod<[], any>,
  '__nextArticleId' : ActorMethod<[], bigint>,
  '__nextCommentId' : ActorMethod<[], bigint>,
  '__nextPinOrder' : ActorMethod<[], bigint>,
  '__registry' : ActorMethod<[], any>,
  '__userProfiles' : ActorMethod<
    [[] | [Principal], [] | [bigint]],
    Array<[Principal, UserProfile]>
  >,
  '_immutableObjectStorageBlobsAreLive' : ActorMethod<
    [Array<Uint8Array>],
    Array<boolean>
  >,
  '_immutableObjectStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_immutableObjectStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_immutableObjectStorageCreateCertificate' : ActorMethod<
    [string],
    _ImmutableObjectStorageCreateCertificateResult
  >,
  '_immutableObjectStorageRefillCashier' : ActorMethod<
    [[] | [_ImmutableObjectStorageRefillInformation]],
    _ImmutableObjectStorageRefillResult
  >,
  '_immutableObjectStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initialize_access_control' : ActorMethod<[], undefined>,
  '_internet_identity_sign_in_finish' : ActorMethod<[], Result>,
  '_internet_identity_sign_in_start' : ActorMethod<[], Uint8Array>,
  'addComment' : ActorMethod<[bigint, string], bigint>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createArticle' : ActorMethod<[string, string, Array<string>], bigint>,
  'deleteArticle' : ActorMethod<[bigint], undefined>,
  'deleteComment' : ActorMethod<[bigint], undefined>,
  'dropFileReference' : ActorMethod<[string], undefined>,
  'getAllArticles' : ActorMethod<[], Array<[bigint, Article]>>,
  'getArticle' : ActorMethod<[bigint], [] | [Article]>,
  'getArticleLikeCount' : ActorMethod<[bigint], bigint>,
  'getArticlesByAuthor' : ActorMethod<[Principal], Array<[bigint, Article]>>,
  'getArticlesByCategory' : ActorMethod<[string], Array<[bigint, Article]>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getCommentsForArticle' : ActorMethod<[bigint], Array<Comment>>,
  'getFileReference' : ActorMethod<[string], [] | [FileReference]>,
  'getTokenBalance' : ActorMethod<[], bigint>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'hasLikedArticle' : ActorMethod<[bigint], boolean>,
  'initializeAccessControl' : ActorMethod<[], undefined>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'isCallerApproved' : ActorMethod<[], boolean>,
  'likeArticle' : ActorMethod<[bigint], undefined>,
  'listApprovals' : ActorMethod<[], Array<UserApprovalInfo>>,
  'listFileReferences' : ActorMethod<[], Array<FileReference>>,
  'registerFileReference' : ActorMethod<[string, string], undefined>,
  'requestApproval' : ActorMethod<[], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'setApproval' : ActorMethod<[Principal, ApprovalStatus], undefined>,
  'setArticlePinned' : ActorMethod<[bigint, boolean], undefined>,
  'setArticleVisible' : ActorMethod<[bigint, boolean, string], undefined>,
  'transferTokens' : ActorMethod<[Principal, bigint], undefined>,
  'unlikeArticle' : ActorMethod<[bigint], undefined>,
  'updateArticle' : ActorMethod<
    [bigint, string, string, Array<string>],
    undefined
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];