/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Time = IDL.Int;
export const Article = IDL.Record({
  'categories' : IDL.Vec(IDL.Text),
  'title' : IDL.Text,
  'likeCount' : IDL.Nat,
  'content' : IDL.Text,
  'submittedForReview' : IDL.Bool,
  'createdAt' : Time,
  'author' : IDL.Principal,
  'approvalStatus' : IDL.Int,
  'updatedAt' : Time,
});
export const GameMod = IDL.Record({
  'title' : IDL.Text,
  'link' : IDL.Text,
  'createdAt' : Time,
  'gameId' : IDL.Nat,
  'description' : IDL.Text,
  'imageUrl' : IDL.Text,
});
export const Land = IDL.Record({
  'x' : IDL.Nat,
  'y' : IDL.Nat,
  'id' : IDL.Nat,
});
export const TradingPair = IDL.Record({
  'enabled' : IDL.Bool,
  'coinId' : IDL.Text,
  'symbol' : IDL.Text,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });
export const Comment = IDL.Record({
  'content' : IDL.Text,
  'commentId' : IDL.Nat,
  'createdAt' : Time,
  'author' : IDL.Principal,
  'articleId' : IDL.Nat,
});
export const FileReference = IDL.Record({
  'hash' : IDL.Text,
  'path' : IDL.Text,
});
export const MiningResult = IDL.Variant({
  'gold' : IDL.Nat,
  'nothing' : IDL.Null,
  'death' : IDL.Null,
});
export const MiningHistory = IDL.Record({
  'result' : MiningResult,
  'landId' : IDL.Nat,
  'timestamp' : Time,
});
export const MiningLeaderboardEntry = IDL.Record({
  'principal' : IDL.Principal,
  'gold' : IDL.Nat,
});
export const PlayerStatus = IDL.Variant({
  'alive' : IDL.Null,
  'dead' : IDL.Null,
});
export const ApprovalStatus = IDL.Variant({
  'pending' : IDL.Null,
  'approved' : IDL.Null,
  'rejected' : IDL.Null,
});
export const UserApprovalInfo = IDL.Record({
  'status' : ApprovalStatus,
  'principal' : IDL.Principal,
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Text)],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func([IDL.Vec(IDL.Text)], [], []),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  'addComment' : IDL.Func([IDL.Nat, IDL.Text], [IDL.Nat], []),
  'addGameMod' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [IDL.Nat],
      [],
    ),
  'addTradingPair' : IDL.Func([IDL.Text, IDL.Text, IDL.Bool], [], []),
  'approveArticle' : IDL.Func([IDL.Nat], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createArticle' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Bool, IDL.Vec(IDL.Text)],
      [IDL.Nat],
      [],
    ),
  'deleteArticle' : IDL.Func([IDL.Nat], [], []),
  'deleteComment' : IDL.Func([IDL.Nat], [], []),
  'deleteTradingPair' : IDL.Func([IDL.Text], [], []),
  'dropFileReference' : IDL.Func([IDL.Text], [], []),
  'getAllArticles' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(IDL.Nat, Article))],
      ['query'],
    ),
  'getAllGameMods' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(IDL.Nat, GameMod))],
      ['query'],
    ),
  'getAllLands' : IDL.Func([], [IDL.Vec(Land)], ['query']),
  'getAllTradingPairs' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(IDL.Text, TradingPair))],
      ['query'],
    ),
  'getArticle' : IDL.Func([IDL.Nat], [IDL.Opt(Article)], ['query']),
  'getArticleLikeCount' : IDL.Func([IDL.Nat], [IDL.Nat], ['query']),
  'getArticlesByAuthor' : IDL.Func(
      [IDL.Principal],
      [IDL.Vec(IDL.Tuple(IDL.Nat, Article))],
      ['query'],
    ),
  'getArticlesByCategory' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(IDL.Tuple(IDL.Nat, Article))],
      ['query'],
    ),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getCommentsForArticle' : IDL.Func([IDL.Nat], [IDL.Vec(Comment)], ['query']),
  'getFileReference' : IDL.Func([IDL.Text], [FileReference], ['query']),
  'getGameModById' : IDL.Func([IDL.Nat], [IDL.Opt(GameMod)], ['query']),
  'getLand' : IDL.Func([IDL.Nat], [IDL.Opt(Land)], ['query']),
  'getLogEnabled' : IDL.Func([], [IDL.Bool], ['query']),
  'getMiningHistory' : IDL.Func([], [IDL.Vec(MiningHistory)], ['query']),
  'getMiningLeaderboard' : IDL.Func(
      [],
      [IDL.Vec(MiningLeaderboardEntry)],
      ['query'],
    ),
  'getMiningProbability' : IDL.Func([], [IDL.Nat, IDL.Nat], ['query']),
  'getPlayerGold' : IDL.Func([], [IDL.Nat], ['query']),
  'getPlayerStatus' : IDL.Func([], [PlayerStatus], ['query']),
  'getTokenBalance' : IDL.Func([], [IDL.Nat], ['query']),
  'getTotalGoldMined' : IDL.Func([], [IDL.Nat], ['query']),
  'getTotalMiningOperations' : IDL.Func([], [IDL.Nat], ['query']),
  'getTotalPlayers' : IDL.Func([], [IDL.Nat], ['query']),
  'getTradingPair' : IDL.Func([IDL.Text], [IDL.Opt(TradingPair)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'hasLikedArticle' : IDL.Func([IDL.Nat], [IDL.Bool], ['query']),
  'initializeAccessControl' : IDL.Func([], [], []),
  'initializeLands' : IDL.Func([], [], []),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'isCallerApproved' : IDL.Func([], [IDL.Bool], ['query']),
  'likeArticle' : IDL.Func([IDL.Nat], [], []),
  'listApprovals' : IDL.Func([], [IDL.Vec(UserApprovalInfo)], ['query']),
  'listFileReferences' : IDL.Func([], [IDL.Vec(FileReference)], ['query']),
  'mineLand' : IDL.Func([IDL.Nat], [MiningResult], []),
  'registerFileReference' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'rejectArticle' : IDL.Func([IDL.Nat], [], []),
  'requestApproval' : IDL.Func([], [], []),
  'revive' : IDL.Func([], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'setApproval' : IDL.Func([IDL.Principal, ApprovalStatus], [], []),
  'setLogEnabled' : IDL.Func([IDL.Bool], [], []),
  'setMiningProbability' : IDL.Func([IDL.Nat, IDL.Nat], [], []),
  'transferTokens' : IDL.Func([IDL.Principal, IDL.Nat], [], []),
  'unlikeArticle' : IDL.Func([IDL.Nat], [], []),
  'updateArticle' : IDL.Func(
      [IDL.Nat, IDL.Text, IDL.Text, IDL.Bool, IDL.Vec(IDL.Text)],
      [],
      [],
    ),
  'updateGameMod' : IDL.Func(
      [IDL.Nat, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [],
      [],
    ),
  'updateTradingPair' : IDL.Func([IDL.Text, IDL.Bool], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Time = IDL.Int;
  const Article = IDL.Record({
    'categories' : IDL.Vec(IDL.Text),
    'title' : IDL.Text,
    'likeCount' : IDL.Nat,
    'content' : IDL.Text,
    'submittedForReview' : IDL.Bool,
    'createdAt' : Time,
    'author' : IDL.Principal,
    'approvalStatus' : IDL.Int,
    'updatedAt' : Time,
  });
  const GameMod = IDL.Record({
    'title' : IDL.Text,
    'link' : IDL.Text,
    'createdAt' : Time,
    'gameId' : IDL.Nat,
    'description' : IDL.Text,
    'imageUrl' : IDL.Text,
  });
  const Land = IDL.Record({ 'x' : IDL.Nat, 'y' : IDL.Nat, 'id' : IDL.Nat });
  const TradingPair = IDL.Record({
    'enabled' : IDL.Bool,
    'coinId' : IDL.Text,
    'symbol' : IDL.Text,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  const Comment = IDL.Record({
    'content' : IDL.Text,
    'commentId' : IDL.Nat,
    'createdAt' : Time,
    'author' : IDL.Principal,
    'articleId' : IDL.Nat,
  });
  const FileReference = IDL.Record({ 'hash' : IDL.Text, 'path' : IDL.Text });
  const MiningResult = IDL.Variant({
    'gold' : IDL.Nat,
    'nothing' : IDL.Null,
    'death' : IDL.Null,
  });
  const MiningHistory = IDL.Record({
    'result' : MiningResult,
    'landId' : IDL.Nat,
    'timestamp' : Time,
  });
  const MiningLeaderboardEntry = IDL.Record({
    'principal' : IDL.Principal,
    'gold' : IDL.Nat,
  });
  const PlayerStatus = IDL.Variant({ 'alive' : IDL.Null, 'dead' : IDL.Null });
  const ApprovalStatus = IDL.Variant({
    'pending' : IDL.Null,
    'approved' : IDL.Null,
    'rejected' : IDL.Null,
  });
  const UserApprovalInfo = IDL.Record({
    'status' : ApprovalStatus,
    'principal' : IDL.Principal,
  });
  
  return IDL.Service({
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Text)],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Text)],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    'addComment' : IDL.Func([IDL.Nat, IDL.Text], [IDL.Nat], []),
    'addGameMod' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [IDL.Nat],
        [],
      ),
    'addTradingPair' : IDL.Func([IDL.Text, IDL.Text, IDL.Bool], [], []),
    'approveArticle' : IDL.Func([IDL.Nat], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createArticle' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Bool, IDL.Vec(IDL.Text)],
        [IDL.Nat],
        [],
      ),
    'deleteArticle' : IDL.Func([IDL.Nat], [], []),
    'deleteComment' : IDL.Func([IDL.Nat], [], []),
    'deleteTradingPair' : IDL.Func([IDL.Text], [], []),
    'dropFileReference' : IDL.Func([IDL.Text], [], []),
    'getAllArticles' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(IDL.Nat, Article))],
        ['query'],
      ),
    'getAllGameMods' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(IDL.Nat, GameMod))],
        ['query'],
      ),
    'getAllLands' : IDL.Func([], [IDL.Vec(Land)], ['query']),
    'getAllTradingPairs' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(IDL.Text, TradingPair))],
        ['query'],
      ),
    'getArticle' : IDL.Func([IDL.Nat], [IDL.Opt(Article)], ['query']),
    'getArticleLikeCount' : IDL.Func([IDL.Nat], [IDL.Nat], ['query']),
    'getArticlesByAuthor' : IDL.Func(
        [IDL.Principal],
        [IDL.Vec(IDL.Tuple(IDL.Nat, Article))],
        ['query'],
      ),
    'getArticlesByCategory' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(IDL.Tuple(IDL.Nat, Article))],
        ['query'],
      ),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getCommentsForArticle' : IDL.Func(
        [IDL.Nat],
        [IDL.Vec(Comment)],
        ['query'],
      ),
    'getFileReference' : IDL.Func([IDL.Text], [FileReference], ['query']),
    'getGameModById' : IDL.Func([IDL.Nat], [IDL.Opt(GameMod)], ['query']),
    'getLand' : IDL.Func([IDL.Nat], [IDL.Opt(Land)], ['query']),
    'getLogEnabled' : IDL.Func([], [IDL.Bool], ['query']),
    'getMiningHistory' : IDL.Func([], [IDL.Vec(MiningHistory)], ['query']),
    'getMiningLeaderboard' : IDL.Func(
        [],
        [IDL.Vec(MiningLeaderboardEntry)],
        ['query'],
      ),
    'getMiningProbability' : IDL.Func([], [IDL.Nat, IDL.Nat], ['query']),
    'getPlayerGold' : IDL.Func([], [IDL.Nat], ['query']),
    'getPlayerStatus' : IDL.Func([], [PlayerStatus], ['query']),
    'getTokenBalance' : IDL.Func([], [IDL.Nat], ['query']),
    'getTotalGoldMined' : IDL.Func([], [IDL.Nat], ['query']),
    'getTotalMiningOperations' : IDL.Func([], [IDL.Nat], ['query']),
    'getTotalPlayers' : IDL.Func([], [IDL.Nat], ['query']),
    'getTradingPair' : IDL.Func([IDL.Text], [IDL.Opt(TradingPair)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'hasLikedArticle' : IDL.Func([IDL.Nat], [IDL.Bool], ['query']),
    'initializeAccessControl' : IDL.Func([], [], []),
    'initializeLands' : IDL.Func([], [], []),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'isCallerApproved' : IDL.Func([], [IDL.Bool], ['query']),
    'likeArticle' : IDL.Func([IDL.Nat], [], []),
    'listApprovals' : IDL.Func([], [IDL.Vec(UserApprovalInfo)], ['query']),
    'listFileReferences' : IDL.Func([], [IDL.Vec(FileReference)], ['query']),
    'mineLand' : IDL.Func([IDL.Nat], [MiningResult], []),
    'registerFileReference' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'rejectArticle' : IDL.Func([IDL.Nat], [], []),
    'requestApproval' : IDL.Func([], [], []),
    'revive' : IDL.Func([], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'setApproval' : IDL.Func([IDL.Principal, ApprovalStatus], [], []),
    'setLogEnabled' : IDL.Func([IDL.Bool], [], []),
    'setMiningProbability' : IDL.Func([IDL.Nat, IDL.Nat], [], []),
    'transferTokens' : IDL.Func([IDL.Principal, IDL.Nat], [], []),
    'unlikeArticle' : IDL.Func([IDL.Nat], [], []),
    'updateArticle' : IDL.Func(
        [IDL.Nat, IDL.Text, IDL.Text, IDL.Bool, IDL.Vec(IDL.Text)],
        [],
        [],
      ),
    'updateGameMod' : IDL.Func(
        [IDL.Nat, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [],
        [],
      ),
    'updateTradingPair' : IDL.Func([IDL.Text, IDL.Bool], [], []),
  });
};

export const init = ({ IDL }) => { return []; };